In [ ]:
print("Hello, I am excited to learn pytorch!")

Hello, I am excited to learn pytorch!


In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


**Tensor**

In [ ]:
# scalar tensor
scalar = torch.tensor(13)
scalar

tensor(13)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

13

In [ ]:
# vector
vector = torch.tensor([3,5])
vector

tensor([3, 5])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 2])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[4,5,1]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [4, 5, 1]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [4, 5, 1]])

In [ ]:
# Random Tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5787, 0.8653, 0.0209, 0.4734],
        [0.0192, 0.3845, 0.7728, 0.1579],
        [0.4418, 0.6882, 0.5525, 0.2832]])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
image_random_tensor = torch.rand(size=(3,224,224))
image_random_tensor

tensor([[[0.1849, 0.6303, 0.6069,  ..., 0.4379, 0.6189, 0.8708],
         [0.7964, 0.5234, 0.0518,  ..., 0.1447, 0.8686, 0.6908],
         [0.8742, 0.8209, 0.7196,  ..., 0.1855, 0.5556, 0.7165],
         ...,
         [0.8090, 0.2342, 0.2774,  ..., 0.2879, 0.5835, 0.1803],
         [0.8786, 0.7505, 0.0929,  ..., 0.9157, 0.2411, 0.0466],
         [0.1486, 0.3335, 0.2045,  ..., 0.3679, 0.3254, 0.8955]],

        [[0.6670, 0.1190, 0.9889,  ..., 0.0238, 0.0884, 0.7318],
         [0.4948, 0.1382, 0.4267,  ..., 0.3900, 0.8336, 0.7993],
         [0.0080, 0.7093, 0.9131,  ..., 0.8950, 0.8876, 0.9741],
         ...,
         [0.8925, 0.9891, 0.2777,  ..., 0.7915, 0.5178, 0.4583],
         [0.2932, 0.6420, 0.8297,  ..., 0.9646, 0.7486, 0.2395],
         [0.3252, 0.2187, 0.1366,  ..., 0.0486, 0.8540, 0.7024]],

        [[0.3413, 0.0166, 0.5367,  ..., 0.7791, 0.0912, 0.1957],
         [0.0020, 0.7820, 0.5514,  ..., 0.2723, 0.0242, 0.2835],
         [0.6943, 0.2370, 0.8435,  ..., 0.4633, 0.1593, 0.

In [ ]:
# zeros and ones
zeros = torch.zeros(4,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#creating a range
t = torch.arange(0,10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.zeros_like(input = t)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor DataType**

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([12,1,3,5,6,7,],dtype=torch.float32
                               ,device=None #
                               ,requires_grad=False)
float_32_tensor

tensor([12.,  1.,  3.,  5.,  6.,  7.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([1,2,3,4,5,5],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3, 4, 5, 5], dtype=torch.int32)

In [ ]:
int_32_tensor*float_32_tensor

tensor([12.,  2.,  9., 20., 30., 35.])

In [ ]:
# getting information from tensor
# to datatype = tensor.dtype
# to get shape = tensor.shape
# to get device = tensor.device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7787, 0.4887, 0.6292, 0.9335],
        [0.6670, 0.4267, 0.7311, 0.7171],
        [0.7929, 0.0192, 0.8115, 0.3318]])

In [ ]:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


In [ ]:
# manipulating tensor (tensor operation)
tensor = torch.tensor([1,4,6])
tensor + 10

tensor([11, 14, 16])

In [ ]:
tensor * 20

tensor([ 20,  80, 120])

In [ ]:
tensor - 10

tensor([-9, -6, -4])

In [ ]:
# pytorch in-built function
torch.mul(tensor,10)

tensor([10, 40, 60])

In [ ]:
torch.add(tensor,5)

tensor([ 6,  9, 11])

In [ ]:
# element wise multiplication
tensor * tensor

tensor([ 1, 16, 36])

In [ ]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(53)

In [ ]:
tensor @ tensor

tensor(53)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1896, 0.3191, 0.2493],
        [0.3379, 0.5908, 0.6168],
        [0.3426, 0.5891, 0.5485]])

In [ ]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# transpose
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
# tensor aggregation : mean, max, min, sum etc
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# finding the postinal min and max
x.argmin() #index of minimum value

tensor(0)

In [ ]:
x.argmax() #index of maximum value

tensor(9)

In [ ]:
# reshaping, stacking, squeezing, unsqueezing tensor
x = torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(5,2)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
x_stacked = torch.stack([x,x,x],dim=1)
x_stacked

tensor([[ 5.,  5.,  5.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])

In [ ]:
print(x_stacked.shape)
print(x_stacked.squeeze().shape)

torch.Size([10, 3])
torch.Size([10, 3])


In [ ]:
x_stacked.unsqueeze(dim=0)

tensor([[[ 5.,  5.,  5.],
         [ 2.,  2.,  2.],
         [ 3.,  3.,  3.],
         [ 4.,  4.,  4.],
         [ 5.,  5.,  5.],
         [ 6.,  6.,  6.],
         [ 7.,  7.,  7.],
         [ 8.,  8.,  8.],
         [ 9.,  9.,  9.],
         [10., 10., 10.]]])

In [ ]:
# premute
x_original= torch.rand(size=(224,224,3))
print(x_original.shape)
x_premuted = x_original.permute(2,0,1)
x_premuted.shape

torch.Size([224, 224, 3])


torch.Size([3, 224, 224])

In [ ]:
#indexing
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
#numpy and tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

In [ ]:
#Reproducbility
torch.rand(3,3)

tensor([[0.0027, 0.9816, 0.3493],
        [0.8916, 0.1394, 0.5189],
        [0.2103, 0.0834, 0.8401]])

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.3688, 0.6422, 0.1196, 0.5172],
        [0.7315, 0.1156, 0.1485, 0.1526],
        [0.9373, 0.1645, 0.1798, 0.6659]])
tensor([[0.7581, 0.8435, 0.8299, 0.6469],
        [0.3702, 0.4214, 0.1159, 0.4204],
        [0.3503, 0.0114, 0.9880, 0.6833]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
# running tensor and pytorch object on GPUs
#getting  a GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# putting tensor on gpu
tensor = torch.tensor([1,2,3,4], device = device)
print(tensor, tensor.device)

tensor([1, 2, 3, 4]) cpu


In [ ]:
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [ ]:
random_tensor2 = torch.rand(1,7)
random_tensor2

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036]])

In [ ]:
random_tensor.matmul(random_tensor2.T)

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [ ]:
torch.manual_seed(0)
random_tensor = torch.rand(7,7)
print(random_tensor)

torch.manual_seed(0)
random_tensor2 = torch.rand(1,7)
print(random_tensor2)

random_tensor @ random_tensor2.T

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])