In [ ]:
# Building model
#linear regression model

import numpy as np
import pandas as pd
import torch
from torch import nn

class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weight = nn.Parameter(torch.randn(1,requires_grad=True,
                                            dtype=torch.float))
    self.bias = nn.Parameter(torch.randn(1,requires_grad=True,
                                         dtype=torch.float))

  def forward(self, X:torch.Tensor)->torch.Tensor:
      return self.weight * X + self.bias



In [ ]:
torch.manual_seed(42)

model_0 = LinearRegressionModel()

model_0

LinearRegressionModel()

In [ ]:
list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [ ]:
model_0.state_dict()

OrderedDict([('weight', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [ ]:
weight = 0.7
bias = 0.3

# Create data
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [ ]:
train_split = int(0.8 * len(X)) # 80% of data used for training set, 20% for testing
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

In [ ]:
with torch.inference_mode():
  y_pred = model_0(X_test)

y_pred

tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]])

In [ ]:
y_test

tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

In [ ]:
#setup loss function
loss_fn = nn.L1Loss()

#setup optimizer
optimizer = torch.optim.SGD(params=model_0.parameters(),lr=0.01)

In [ ]:
# building a training loop (and testing loop) in pytorch

epochs=200
epoch_count = []
loss_value = []
test_loss_v = []

for epoch in range(epochs):
  # set the model to taining mode
  model_0.train()

  #forward pass
  y_pred = model_0(X_train)

  #calcualte the loss
  loss = loss_fn(y_pred,y_train)
  print(f"loss :{loss}")

  #optimizer zero grad
  optimizer.zero_grad()

  # perform backpropgation on the loss with respect to the parameter
  loss.backward()

  #step the optimizer (perform gradient descent)
  optimizer.step()


  model_0.eval() #turns off different settings in the model that is not required for testing
  with torch.inference_mode():
    # do forward pass
    test_pred = model_0(X_test)

    #2. calculate the loss
    test_loss = loss_fn(test_pred,y_test)

  if epoch%10==0:
    epoch_count.append(epoch)
    loss_value.append(loss)
    test_loss_v.append(test_loss)
    print(f"Epoch :{epoch} | loss: {loss} | Test loss: {test_loss}")
    print(model_0.state_dict())

loss :0.31288138031959534
Epoch :0 | loss: 0.31288138031959534 | Test loss: 0.48106518387794495
OrderedDict([('weight', tensor([0.3406])), ('bias', tensor([0.1388]))])
loss :0.3013603389263153
loss :0.28983935713768005
loss :0.2783183455467224
loss :0.26679736375808716
loss :0.2552763521671295
loss :0.24375534057617188
loss :0.23223432898521423
loss :0.22071333229541779
loss :0.20919232070446014
loss :0.1976713240146637
Epoch :10 | loss: 0.1976713240146637 | Test loss: 0.3463551998138428
OrderedDict([('weight', tensor([0.3796])), ('bias', tensor([0.2388]))])
loss :0.18615034222602844
loss :0.1746293306350708
loss :0.16310831904411316
loss :0.1515873372554779
loss :0.14006635546684265
loss :0.1285453587770462
loss :0.11702437698841095
loss :0.1060912236571312
loss :0.09681284427642822
loss :0.08908725529909134
Epoch :20 | loss: 0.08908725529909134 | Test loss: 0.21729660034179688
OrderedDict([('weight', tensor([0.4184])), ('bias', tensor([0.3333]))])
loss :0.08227583020925522
loss :0.07

In [ ]:
loss_value

[tensor(0.3129, grad_fn=<MeanBackward0>),
 tensor(0.1977, grad_fn=<MeanBackward0>),
 tensor(0.0891, grad_fn=<MeanBackward0>),
 tensor(0.0531, grad_fn=<MeanBackward0>),
 tensor(0.0454, grad_fn=<MeanBackward0>),
 tensor(0.0417, grad_fn=<MeanBackward0>),
 tensor(0.0382, grad_fn=<MeanBackward0>),
 tensor(0.0348, grad_fn=<MeanBackward0>),
 tensor(0.0313, grad_fn=<MeanBackward0>),
 tensor(0.0279, grad_fn=<MeanBackward0>),
 tensor(0.0245, grad_fn=<MeanBackward0>),
 tensor(0.0210, grad_fn=<MeanBackward0>),
 tensor(0.0176, grad_fn=<MeanBackward0>),
 tensor(0.0142, grad_fn=<MeanBackward0>),
 tensor(0.0107, grad_fn=<MeanBackward0>),
 tensor(0.0073, grad_fn=<MeanBackward0>),
 tensor(0.0039, grad_fn=<MeanBackward0>),
 tensor(0.0089, grad_fn=<MeanBackward0>),
 tensor(0.0089, grad_fn=<MeanBackward0>),
 tensor(0.0089, grad_fn=<MeanBackward0>)]

In [ ]:
list(model_0.parameters())

[Parameter containing:
 tensor([0.6990], requires_grad=True),
 Parameter containing:
 tensor([0.3093], requires_grad=True)]

In [ ]:
with torch.inference_mode():
  y_preds_new = model_0(X_test)

print(y_preds_new)

tensor([[0.8685],
        [0.8825],
        [0.8965],
        [0.9105],
        [0.9245],
        [0.9384],
        [0.9524],
        [0.9664],
        [0.9804],
        [0.9944]])


In [ ]:
#saving and loading model in pytorch
from pathlib import Path

#creating model directory
MODEL_PATH = Path('models')
MODEL_PATH.mkdir(parents=True,exist_ok=True)

#create model save path
MODEL_NAME='01_pytorch_workflow_model_0.pth'
MODEL_SAVE_PATH = MODEL_PATH / MODEL_NAME

# save the model state_dict
print(f"saving model to path : {MODEL_SAVE_PATH}")
torch.save(obj=model_0.state_dict(),f=MODEL_SAVE_PATH)

saving model to path : models/01_pytorch_workflow_model_0.pth


In [ ]:
!ls -l models

total 4
-rw-r--r-- 1 root root 1680 Aug 23 11:42 01_pytorch_workflow_model_0.pth


In [ ]:
# loading save model
loaded_model_0 = LinearRegressionModel()

# load the saved state_dict()
loaded_model_0.load_state_dict(torch.load(f=MODEL_SAVE_PATH))

<All keys matched successfully>

In [ ]:
loaded_model_0.state_dict()

OrderedDict([('weight', tensor([0.6990])), ('bias', tensor([0.3093]))])

In [ ]:
loaded_model_0.eval()
with torch.inference_mode():
  loaded_model_pred = loaded_model_0(X_test)

In [ ]:
y_preds_new == loaded_model_pred

tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True]])